export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const FETCH_INTEGRATION_STEPS_REQUEST =
  "FETCH_INTEGRATION_STEPS_REQUEST";
export const FETCH_INTEGRATION_STEPS_SUCCESS =
  "FETCH_INTEGRATION_STEPS_SUCCESS";
export const FETCH_INTEGRATION_STEPS_FAILURE =
  "FETCH_INTEGRATION_STEPS_FAILURE";

// Merchant Login Types
export const MERCHANT_LOGIN_REQUEST = "MERCHANT_LOGIN_REQUEST";
export const MERCHANT_LOGIN_SUCCESS = "MERCHANT_LOGIN_SUCCESS";
export const MERCHANT_LOGIN_FAILURE = "MERCHANT_LOGIN_FAILURE";

// Merchant Register Types
export const MERCHANT_REGISTER_REQUEST = "MERCHANT_REGISTER_REQUEST";
export const MERCHANT_REGISTER_SUCCESS = "MERCHANT_REGISTER_SUCCESS";
export const MERCHANT_REGISTER_FAILURE = "MERCHANT_REGISTER_FAILURE";

// Merchant FAQ
export const MERCHANT_FAQ_REQUEST = "MERCHANT_FAQ_REQUEST";
export const MERCHANT_FAQ_SUCCESS = "MERCHANT_FAQ_SUCCESS";
export const MERCHANT_FAQ_FAILURE = "MERCHANT_FAQ_FAILURE";

// Merchant Contact Us
export const MERCHANT_CONTACT_US_REQUEST = "MERCHANT_CONTACT_US_REQUEST";
export const MERCHANT_CONTACT_US_SUCCESS = "MERCHANT_CONTACT_US_SUCCESS";
export const MERCHANT_CONTACT_US_FAILURE = "MERCHANT_CONTACT_US_FAILURE";

// Merchant Dashboard
export const MERCHANT_DASHBOARD_REQUEST = "MERCHANT_DASHBOARD_REQUEST";
export const MERCHANT_DASHBOARD_SUCCESS = "MERCHANT_DASHBOARD_SUCCESS";
export const MERCHANT_DASHBOARD_FAILURE = "MERCHANT_DASHBOARD_FAILURE";

// Merchant Invoice Details
export const MERCHANT_INVOICE_DETAILS_REQUEST =
  "MERCHANT_INVOICE_DETAILS_REQUEST";
export const MERCHANT_INVOICE_DETAILS_SUCCESS =
  "MERCHANT_INVOICE_DETAILS_SUCCESS";
export const MERCHANT_INVOICE_DETAILS_FAILURE =
  "MERCHANT_INVOICE_DETAILS_FAILURE";

// Merchant Update Profile
export const MERCHANT_UPDATE_PROFILE_REQUEST =
  "MERCHANT_UPDATE_PROFILE_REQUEST";
export const MERCHANT_UPDATE_PROFILE_SUCCESS =
  "MERCHANT_UPDATE_PROFILE_SUCCESS";
export const MERCHANT_UPDATE_PROFILE_FAILURE =
  "MERCHANT_UPDATE_PROFILE_FAILURE";

// Merchant Get Profile
export const MERCHANT_GET_PROFILE_REQUEST = "MERCHANT_GET_PROFILE_REQUEST";
export const MERCHANT_GET_PROFILE_SUCCESS = "MERCHANT_GET_PROFILE_SUCCESS";
export const MERCHANT_GET_PROFILE_FAILURE = "MERCHANT_GET_PROFILE_FAILURE";

// Merchant Get All Store
export const MERCHANT_GET_ALL_STORES_REQUEST =
  "MERCHANT_GET_ALL_STORES_REQUEST";
export const MERCHANT_CLEAR_ALL_STORES = "MERCHANT_CLEAR_ALL_STORES";
export const MERCHANT_GET_ALL_STORES_SUCCESS =
  "MERCHANT_GET_ALL_STORES_SUCCESS";
export const MERCHANT_GET_ALL_STORES_FAILURE =
  "MERCHANT_GET_ALL_STORES_FAILURE";
export const RERENDER_FILE_UPLOAD_CONTROL = "RERENDER_FILE_UPLOAD_CONTROL";
export const MERCHANT_STORE_HASH_MORE = "MERCHANT_STORE_HASH_MORE";

// Merchant Update Store
export const MERCHANT_UPDATE_STORE_REQUEST = "MERCHANT_UPDATE_STORE_REQUEST";
export const MERCHANT_UPDATE_STORE_SUCCESS = "MERCHANT_UPDATE_STORE_SUCCESS";
export const MERCHANT_UPDATE_STORE_FAILURE = "MERCHANT_UPDATE_STORE_FAILURE";

// Merchant Invoice by Customer id
export const MERCHANT_INVOICE_REQUEST = "MERCHANT_INVOICE_REQUEST";
export const MERCHANT_INVOICE_SUCCESS = "MERCHANT_INVOICE_SUCCESS";
export const MERCHANT_INVOICE_FAILURE = "MERCHANT_INVOICE_FAILURE";

// Merchant Subscription plans
export const MERCHANT_SUBSCRIPTION_PLANS_REQUEST =
  "MERCHANT_SUBSCRIPTION_PLANS_REQUEST";
export const MERCHANT_SUBSCRIPTION_PLANS_SUCCESS =
  "MERCHANT_SUBSCRIPTION_PLANS_SUCCESS";
export const MERCHANT_SUBSCRIPTION_PLANS_FAILURE =
  "MERCHANT_SUBSCRIPTION_PLANS_FAILURE";

// Merchant POS Name
export const MERCHANT_POS_NAME_REQUEST = "MERCHANT_POS_NAME_REQUEST";
export const MERCHANT_POS_NAME_SUCCESS = "MERCHANT_POS_NAME_SUCCESS";
export const MERCHANT_POS_NAME_FAILURE = "MERCHANT_POS_NAME_FAILURE";

// Merchant Loyverse
export const MERCHANT_LOYVERSE_CODE_REQUEST = "MERCHANT_LOYVERSE_CODE_REQUEST";
export const MERCHANT_LOYVERSE_CODE_SUCCESS = "MERCHANT_LOYVERSE_CODE_SUCCESS";
export const MERCHANT_LOYVERSE_CODE_FAILURE = "MERCHANT_LOYVERSE_CODE_FAILURE";

// Partner Dashboard
export const PARTNER_DASHBOARD_REQUEST = "PARTNER_DASHBOARD_REQUEST";
export const PARTNER_DASHBOARD_SUCCESS = "PARTNER_DASHBOARD_SUCCESS";
export const PARTNER_DASHBOARD_FAILURE = "PARTNER_DASHBOARD_FAILURE";

// Partner Update Profile
export const PARTNER_UPDATE_PROFILE_REQUEST = "PARTNER_UPDATE_PROFILE_REQUEST";
export const PARTNER_UPDATE_PROFILE_SUCCESS = "PARTNER_UPDATE_PROFILE_SUCCESS";
export const PARTNER_UPDATE_PROFILE_FAILURE = "PARTNER_UPDATE_PROFILE_FAILURE";

// Partner Get Profile
export const PARTNER_GET_PROFILE_REQUEST = "PARTNER_GET_PROFILE_REQUEST";
export const PARTNER_GET_PROFILE_SUCCESS = "PARTNER_GET_PROFILE_SUCCESS";
export const PARTNER_GET_PROFILE_FAILURE = "PARTNER_GET_PROFILE_FAILURE";

// Partner Get Profile
export const PARTNER_GET_BANK_DETAILS_REQUEST =
  "PARTNER_GET_BANK_DETAILS_REQUEST";
export const PARTNER_GET_BANK_DETAILS_SUCCESS =
  "PARTNER_GET_BANK_DETAILS_SUCCESS";
export const PARTNER_GET_BANK_DETAILS_FAILURE =
  "PARTNER_GET_BANK_DETAILS_FAILURE";

// Partner FAQ
export const PARTNER_FAQ_REQUEST = "PARTNER_FAQ_REQUEST";
export const PARTNER_FAQ_SUCCESS = "PARTNER_FAQ_SUCCESS";
export const PARTNER_FAQ_FAILURE = "PARTNER_FAQ_FAILURE";

// Partner Contact Us
export const PARTNER_CONTACT_US_REQUEST = "PARTNER_CONTACT_US_REQUEST";
export const PARTNER_CONTACT_US_SUCCESS = "PARTNER_CONTACT_US_SUCCESS";
export const PARTNER_CONTACT_US_FAILURE = "PARTNER_CONTACT_US_FAILURE";

export const TERMS_AND_CONDITIONS_REQUEST = "TERMS_AND_CONDITIONS_REQUEST";
export const TERMS_AND_CONDITIONS_SUCCESS = "TERMS_AND_CONDITIONS_SUCCESS";
export const TERMS_AND_CONDITIONS_FAILURE = "TERMS_AND_CONDITIONS_FAILURE";

export const PRIVACY_POLICY_REQUEST = "PRIVACY_POLICY_REQUEST";
export const PRIVACY_POLICY_SUCCESS = "PRIVACY_POLICY_SUCCESS";
export const PRIVACY_POLICY_FAILURE = "PRIVACY_POLICY_FAILURE";

export const CANCELLATION_POLICY_REQUEST = "CANCELLATION_POLICY_REQUEST";
export const CANCELLATION_POLICY_SUCCESS = "CANCELLATION_POLICY_SUCCESS";
export const CANCELLATION_POLICY_FAILURE = "CANCELLATION_POLICY_FAILURE";

// Forgot password
export const FORGOT_PASSWORD_REQUEST = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_FAILURE = "FORGOT_PASSWORD_FAILURE";

//Change Password
export const CHANGE_PASSWORD_REQUEST = "CHANGE_PASSWORD_REQUEST";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_FAILURE = "CHANGE_PASSWORD_FAILURE";

// Merchant Update Logo
export const MERCHANT_UPDATE_LOGO_REQUEST = "MERCHANT_UPDATE_LOGO_REQUEST";
export const MERCHANT_UPDATE_LOGO_SUCCESS = "MERCHANT_UPDATE_LOGO_SUCCESS";
export const MERCHANT_UPDATE_LOGO_FAILURE = "MERCHANT_UPDATE_LOGO_FAILURE";

export const MERCHANT_RESET_PROFILE_COMPLETION =
  "MERCHANT_RESET_PROFILE_COMPLETION";

//Customer
export const CUSTOMER_SIGNUP_REQUEST = "CUSTOMER_SIGNUP_REQUEST";
export const CUSTOMER_SIGNUP_SUCCESS = "CUSTOMER_SIGNUP_SUCCESS";
export const CUSTOMER_SIGNUP_FAILURE = "CUSTOMER_SIGNUP_FAILURE";

export const CUSTOMER_SIGNIN_REQUEST = "CUSTOMER_SIGNIN_REQUEST";
export const CUSTOMER_SIGNIN_SUCCESS = "CUSTOMER_SIGNIN_SUCCESS";
export const CUSTOMER_SIGNIN_FAILURE = "CUSTOMER_SIGNIN_FAILURE";

export const CUSTOMER_VERIFY_OTP_REQUEST = "CUSTOMER_VERIFY_OTP_REQUEST";
export const CUSTOMER_VERIFY_OTP_SUCCESS = "CUSTOMER_VERIFY_OTP_SUCCESS";
export const CUSTOMER_VERIFY_OTP_FAILURE = "CUSTOMER_VERIFY_OTP_FAILURE";

export const CUSTOMER_RESEND_OTP_REQUEST = "CUSTOMER_RESEND_OTP_REQUEST";
export const CUSTOMER_RESEND_OTP_SUCCESS = "CUSTOMER_RESEND_OTP_SUCCESS";
export const CUSTOMER_RESEND_OTP_FAILURE = "CUSTOMER_RESEND_OTP_FAILURE";

export const CUSTOMER_GET_ALL_TRANSACATIONS_REQUEST =
  "CUSTOMER_GET_ALL_TRANSACATIONS_REQUEST";
export const CUSTOMER_GET_ALL_TRANSACATIONS_SUCCESS =
  "CUSTOMER_GET_ALL_TRANSACATIONS_SUCCESS";
export const CUSTOMER_GET_ALL_TRANSACATIONS_FAILURE =
  "CUSTOMER_GET_ALL_TRANSACATIONS_FAILURE";

export const CUSTOMER_GET_SINGLE_TRANSACATION_REQUEST =
  "CUSTOMER_GET_SINGLE_TRANSACATION_REQUEST";
export const CUSTOMER_GET_SINGLE_TRANSACATION_SUCCESS =
  "CUSTOMER_GET_SINGLE_TRANSACATION_SUCCESS";
export const CUSTOMER_GET_SINGLE_TRANSACATION_FAILURE =
  "CUSTOMER_GET_SINGLE_TRANSACATION_FAILURE";

export const CUSTOMER_DETAILS_REQUEST = "CUSTOMER_DETAILS_REQUEST";
export const CUSTOMER_DETAILS_SUCCESS = "CUSTOMER_DETAILS_SUCCESS";
export const CUSTOMER_DETAILS_FAILURE = "CUSTOMER_DETAILS_FAILURE";

// CUSTOMER FAQ
export const CUSTOMER_FAQ_REQUEST = "CUSTOMER_FAQ_REQUEST";
export const CUSTOMER_FAQ_SUCCESS = "CUSTOMER_FAQ_SUCCESS";
export const CUSTOMER_FAQ_FAILURE = "CUSTOMER_FAQ_FAILURE";

// CUSTOMER Contact Us
export const CUSTOMER_CONTACT_US_REQUEST = "CUSTOMER_CONTACT_US_REQUEST";
export const CUSTOMER_CONTACT_US_SUCCESS = "CUSTOMER_CONTACT_US_SUCCESS";
export const CUSTOMER_CONTACT_US_FAILURE = "CUSTOMER_CONTACT_US_FAILURE";

export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";

export const SET_SHOW_PASSWORD = "SET_SHOW_PASSWORD";
export const SET_IS_NEW_USER = "SET_IS_NEW_USER";

export const CLEAR_MERCHANT_TABLE_DATA = "CLEAR_MERCHANT_TABLE_DATA";
export const CLEAR_PARTNER_TABLE_DATA = "CLEAR_PARTNER_TABLE_DATA";

// CUSTOMER RESET PASSWORD
export const CUSTOMER_RESET_PASSWORD_REQUEST =
  "CUSTOMER_RESET_PASSWORD_REQUEST";
export const CUSTOMER_RESET_PASSWORD_SUCCESS =
  "CUSTOMER_RESET_PASSWORD_SUCCESS";
export const CUSTOMER_RESET_PASSWORD_FAILURE =
  "CUSTOMER_RESET_PASSWORD_FAILURE";

export const COMMON_STATISTICS_REQUEST = "COMMON_STATISTICS_REQUEST";
export const COMMON_STATISTICS_SUCCESS = "COMMON_STATISTICS_SUCCESS";
export const COMMON_STATISTICS_FAILURE = "COMMON_STATISTICS_FAILURE";

export const UPDATE_TOKEN = "UPDATE_TOKEN";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const MERCHANT_PAYMENT_HISTORY_REQUEST =
  "MERCHANT_PAYMENT_HISTORY_REQUEST";
export const UPDATE_WALLET_BALANCE = "UPDATE_WALLET_BALANCE";
export const MERCHANT_PAYMENT_HISTORY_SUCCESS =
  "MERCHANT_PAYMENT_HISTORY_SUCCESS";
export const MERCHANT_PAYMENT_HISTORY_RESET = "MERCHANT_PAYMENT_HISTORY_RESET";
export const MERCHANT_PAYMENT_HISTORY_FAILURE =
  "MERCHANT_PAYMENT_HISTORY_FAILURE";

export const CLEAR_MERCHANT_DETAILS = "CLEAR_MERCHANT_DETAILS";

export const CLEAR_MERCHANT_PROFILE = "CLEAR_MERCHANT_PROFILE";

export const MERCHANT_IMPORT_CUSTOMERS_REQUEST =
  "MERCHANT_IMPORT_CUSTOMERS_REQUEST";
export const MERCHANT_IMPORT_CUSTOMERS_SUCCESS =
  "MERCHANT_IMPORT_CUSTOMERS_SUCCESS";
export const MERCHANT_IMPORT_CUSTOMERS_FAILURE =
  "MERCHANT_IMPORT_CUSTOMERS_FAILURE";

export const MERCHANT_FAILED_TRANSACTIONS_REQUEST =
  "MERCHANT_FAILED_TRANSACTIONS_REQUEST";
export const MERCHANT_FAILED_TRANSACTIONS_SUCCESS =
  "MERCHANT_FAILED_TRANSACTIONS_SUCCESS";
export const MERCHANT_FAILED_TRANSACTIONS_FAILURE =
  "MERCHANT_FAILED_TRANSACTIONS_FAILURE";

export const MERCHANT_FAILED_TRANSACTIONS_RESEND_REQUEST =
  "MERCHANT_FAILED_TRANSACTIONS_RESEND_REQUEST";
export const MERCHANT_FAILED_TRANSACTIONS_RESEND_SUCCESS =
  "MERCHANT_FAILED_TRANSACTIONS_RESEND_SUCCESS";
export const MERCHANT_FAILED_TRANSACTIONS_RESEND_FAILURE =
  "MERCHANT_FAILED_TRANSACTIONS_RESEND_FAILURE";

export const ADMIN_DASHBOARD_REQUEST = "ADMIN_DASHBOARD_REQUEST";
export const ADMIN_DASHBOARD_SUCCESS = "ADMIN_DASHBOARD_SUCCESS";
export const ADMIN_DASHBOARD_FAILURE = "ADMIN_DASHBOARD_FAILURE";

export const MERCHANT_SUBSCRIPTIONS_PRICING_REQUEST =
  "MERCHANT_SUBSCRIPTIONS_PRICING_REQUEST";
export const MERCHANT_SUBSCRIPTIONS_PRICING_SUCCESS =
  "MERCHANT_SUBSCRIPTIONS_PRICING_SUCCESS";
export const MERCHANT_SUBSCRIPTIONS_PRICING_FAILURE =
  "MERCHANT_SUBSCRIPTIONS_PRICING_FAILURE";

export const MANAGE_PRODUCT_SHOW = "MANAGE_PRODUCT_SHOW";
export const MANAGE_PRODUCT_SUCCESS = "MANAGE_PRODUCT_SUCCESS";
export const MANAGE_PRODUCT_FAILURE = "MANAGE_PRODUCT_FAILURE";
export const MANAGE_PRODUCT_LIST_OFFSET = "MANAGE_PRODUCT_LIST_OFFSET";
export const MANAGE_PRODUCT_SEARCH_TEXT = "MANAGE_PRODUCT_SEARCH_TEXT";
export const MANAGE_PRODUCT_AUTO_COMPLETE_API_LOAD =
  "MANAGE_PRODUCT_AUTO_COMPLETE_API_LOAD";
export const MANAGE_LOADER_HIDE = "MANAGE_LOADER_HIDE";
export const MANAGE_PRODUCT_RESET = "MANAGE_PRODUCT_RESET";
export const MANAGE_PRODUCT_ACTIVE_ROW_ID = "MANAGE_PRODUCT_ACTIVE_ROW_ID";
export const GET_ALL_PRICING_SUCCESS = "GET_ALL_PRICING_SUCCESS";
export const MERCHANT_NEW_PRICING_PAYMENT_HISTORY_SUCCESS =
  "MERCHANT_NEW_PRICING_PAYMENT_HISTORY_SUCCESS";
export const MERCHANT_ALL_COUNTRY_PRICING = "MERCHANT_ALL_COUNTRY_PRICING";
export const MERCHANT_NEW_PRICING_PAYMENT_HISTORY_RESET =
  "MERCHANT_NEW_PRICING_PAYMENT_HISTORY_RESET";
export const GET_STORE_DETAIL = "GET_STORE_DETAIL";

// Error
export const SET_ERROR = "SET_ERROR";
export const CUSTOMER_GUEST_API_ERROR = "CUSTOMER_GUEST_API_ERROR";

//API CALL
export const SET_API_CALL_START = "SET_API_CALL_START";
export const SET_API_CALL_DONE = "SET_API_CALL_DONE";

//Customer
export const CUSTOMER_RECEIPTS_BY_CODE = "CUSTOMER_RECEIPTS_BY_CODE";

export const REDUX_USER_TYPE = "REDUX_USER_TYPE";

export const LANGUAGE_TRANSLATION = "LANGUAGE_TRANSLATION";
export const GET_WHATSAPP_TEMPLATE_LANGUAGE = "GET_WHATSAPP_TEMPLATE_LANGUAGE";
export const SALE_RECEIPT_SETTING = "SALE_RECEIPT_SETTING";
