import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/index.css";
import StoreProvider from "@/app/StoreProvider";
import CustomerDashboardLayout from "@/components/pages/customer/layout";

export const metadata = {
  title: "E-Com",
  description: "Generated by Jemish",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body className="position-relative">
        <StoreProvider>
          <CustomerDashboardLayout>{children}</CustomerDashboardLayout>
        </StoreProvider>
      </body>
    </html>
  );
}
