import "bootstrap/dist/css/bootstrap.min.css";
import "@/styles/index.css";
import Layout from "@/components/layout";
import StoreProvider from "./StoreProvider";

export const metadata = {
  title: "E-Com",
  description: "Generated by Jemish",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/images/favicon.ico" />
      </head>
      <body className="position-relative">
        <StoreProvider>
          <Layout>{children}</Layout>
        </StoreProvider>
      </body>
    </html>
  );
}
